### ISSUE TITLE
[meta] OpenTracing archiving

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#1039]
Let's use this issue to coordinate / discuss the main work items related to completing the archiving of [OpenTracing][OpenTracing org].

- [x] #1037
- [ ] [OpenTracing org] related subtasks:
  - [x] https://github.com/opentracing/opentracing.io/pull/461
  - [x] #1316
  - [ ] Officially archive the https://github.com/opentracing/opentracing.io repo
  - [ ] Reduce the website to a single page?
  - [ ] ...

(As discussed during 22/01/13 Comms meeting.)

[OpenTracing org]: https://github.com/opentracing

**Comment by cartermp** [comment]
@chalin should this still stay open? Each specific subtask (sans the `...` one) is marked complete.

**Comment by chalin** [comment]
@cartermp - I've added a few more items. (We probably won't be able to close this until 23Q1, based on info I've received from elsewhere).

**Comment by chalin** [comment]
Just met with @caniszczyk. We can consider this done.
