### ISSUE TITLE
22Q3-Q4 planning and work log

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#1511]
### Note: some issues listed here are **multi-step tracking issues**. Open the issue to see steps and progress.

☑️ **Done** (selected).

For a **complete list**, see [closed 22Q3-Q4 PRs]

- [x] #1039
- [x] #1574
- [x] #730, now that Ruby docs have been migrated
- [x] #906
  - Will track longer-term subtask separately: https://github.com/open-telemetry/opentelemetry-specification/issues/2558
- [x] #712
- [x] #1519
- [x]  #1515
- [x] #1201
- [x] #925 -- @tedsuo et all
- [x] #1517
- [x] ...

**Prev/next**:

- #1266
- #2163

---

🟢 **Active**ly being worked on:

- [ ] ...

🟡 **Top / next** to do:

- [ ] #1636
- [ ] #668
- [ ] #1052
- [ ] #1194
- [ ] #1063
- [ ] #1635

🔴 **Blocked/awaiting**:

- [ ] #833
  - [ ] #1109
- [ ] ...

🟠 **Ongoing**:

- [ ] #833
- [ ] #1170
- [ ] #1149
- [ ] #744
- [ ] #949
- [ ] #669
- [ ] #948
- [ ] #1268

🟠 **Other** to do:

- [ ] #896
- [ ] #897
- [ ] Make a copyedit pass over #1211

~_Reorder items above using drag-and-drop_~ (Drag-and-drop doesn't seem to work anymore.)

[closed 22Q3-Q4 PRs]: https://github.com/open-telemetry/opentelemetry.io/pulls?q=is%3Apr+is%3Aclosed+author%3Achalin+created%3A%3E%3D2022-04-01++closed%3A%3C%3D2022-12-31+

**Comment by chalin** [comment]
As of 2022/08/21, here are the [infrastructure tasks] (high & medium priority) in order of decreasing priority (from @svrnm via [#otel-comms Slack discussion], +1 by @cartermp):

1. GDPR
1. Policies for redirects for deleted pages
1. Check For External Links
1. Section Parameters
1. Markdown Checks
1. Tooling for code excerpts

I'll update the **Top/next to do** ordered list in the opening comment to reflect this. /cc @austinlparker 

[infrastructure tasks]: https://github.com/open-telemetry/opentelemetry.io/issues?q=is%3Aissue+is%3Aopen+label%3Ainfrastructure+-label%3Ap3-low
[#otel-comms Slack discussion]: https://cloud-native.slack.com/archives/C02UN96HZH6/p1661087711865909?thread_ts=1660924102.517879&cid=C02UN96HZH6
