### ISSUE TITLE
Logs Bridge API & SDK stable meta issue

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#2547]
With the logs bridge api & sdk going stable soon, we have a few high value items identified we should deliver soon throughout the docs:

- [ ] A blog post on them being stable
- [ ] Concept page on logs needs some major rework
- [ ] Documentation for those languages where the API&SDKs are ready (is it only java as of now?)
- [ ] Collector docs on receivers for certain existing log tech
