### ISSUE TITLE
[Meta] Sampling

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#2548]
Add basic documentation for all languages about Sampling:

* [x] JavaScript (https://opentelemetry.io/docs/instrumentation/js/sampling/) use as reference
* [x] Ruby (https://github.com/open-telemetry/opentelemetry.io/pull/2505)
* [ ] Python (WIP: https://github.com/open-telemetry/opentelemetry.io/pull/2485)
* [ ] C++
* [ ] .NET
* [x] Erlang/Elixir (https://github.com/open-telemetry/opentelemetry.io/pull/2556)
* [x] Go
* [ ] Java
* [ ] PHP
* [ ] Rust
* [ ] Swift

# Note

To implement this for a new language, please take a documentation from an existing language (https://opentelemetry.io/docs/instrumentation/go/sampling/ or https://opentelemetry.io/docs/instrumentation/js/sampling/) and adjust it for the language you picked

**Comment by mahitha00** [comment]
is  issue still open

**Comment by svrnm** [comment]
> is issue still open

yes, this still needs to be resolved for some of the languages.

**Comment by SylvanasGr** [comment]
Hello @svrnm,

I hope you're doing well! I've just made my first contribution by opening PR #4199 . Whenever you find a moment, could you kindly review it?

Thank you so much for your time and assistance!

**Comment by svrnm** [comment]
> I hope you're doing well! I've just made my first contribution by opening PR #4199 . Whenever you find a moment, could you kindly review it?

Thank you. Looks like @cartermp already took a look :-)
