### ISSUE TITLE
[Meta] Make the "Roll the dice" application the default sample application

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#2623]
The [Python Getting Started](https://opentelemetry.io/docs/instrumentation/python/getting-started/) has a very simple but great sample application, where instead of just giving back a "hello world", it rolls a virtual dice and returns the value of that. I think we should use that as a sample for ALL of our getting started guides, because later in the manual instrumentation it can be used to add some custom stuff easily:

* Custom span attribute for the number rolled
* Some custom metrics for the numbers rolled individually & totally
* We can add logs (see java example) easily, which for example is not given with the grpc sample

I created 2 updated version for Node.JS & Java:

https://github.com/open-telemetry/opentelemetry.io/pull/2624
https://github.com/open-telemetry/opentelemetry.io/pull/2625

For Java the additional advantage is that we can show logs, which is not available for the gRPC sample used 

Background:
This is inspired by the work we did for the talk we did during KubeCon EU (see the sample app [here](https://github.com/pavolloffay/kubecon-eu-2023-opentelemetry-kubernetes-tutorial/tree/main/app)) and I wanted to give some of that back to the docs. We might even consider to build on top of that in the Operator Docs, but that's another discussion)

-- 

Tracking:

- [x] C++
- [x] .NET
- [x] [Erlang/Elixir](https://github.com/open-telemetry/opentelemetry.io/pull/2685)
- [x] Go
- [x] [Java](https://github.com/open-telemetry/opentelemetry.io/pull/2625)
- [x] [JavaScript](https://github.com/open-telemetry/opentelemetry.io/pull/2624)
- [x] [PHP](#2758)
- [x] Python
- [x] [Ruby](https://github.com/open-telemetry/opentelemetry.io/pull/2655)
- [x] [Rust](https://github.com/open-telemetry/opentelemetry.io/pull/3123)
- [x] Swift

**Comment by austinlparker** [comment]
sgtm. ++ consistency

**Comment by cartermp** [comment]
Yep let's do that

**Comment by tsloughter** [comment]
+1 I already implemented this and planned to introduce it into the Erlang/Elixir docs soon. Had been meaning to check if there was desire to make it the default used by all languages :)

**Comment by tsloughter** [comment]
Including a client would be nice. It may be too much for the docs but to have in the examples for each language would at least be useful.

**Comment by svrnm** [comment]
> Including a client would be nice. It may be too much for the docs but to have in the examples for each language would at least be useful.

what do you mean by a client? A small app that calls that particular service? What would be the advantage over simply using curl?

**Comment by tsloughter** [comment]
Yes, a small http app in the language that calls the dice server. It would demonstrate propagation. Again, I could see it being more code and concepts than is wanted in a "getting started" page.

**Comment by svrnm** [comment]
Agreed, for the getting started it might be "too much code", but I think for further pages around context propagation, etc having a second component in the mix would be helpful. My thought was to eventually reproduce some parts of what we did [here](https://github.com/pavolloffay/kubecon-eu-2023-opentelemetry-kubernetes-tutorial/blob/main/03-app-instrumentation.md) (a frontend calling 2 backends rolling the dice, and then comparing results and announce a winner), but a 2 tier (client->server) would be a little bit simpler.

**Comment by pellared** [comment]
I can try doing it for Go (assigning myself).

**Comment by svrnm** [comment]
All done except C++ 🎉

**Comment by svrnm** [comment]
We did it, all Getting Started guides now use the sample example :tada: 

There is still a lot of work that needs to be done, but I will close this issue to anticipate that accomplishement
