### ISSUE TITLE
Adjust to move of OTLP specs into opentelemetry-proto

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry.io#2642]
We are [moving OTLP spec](https://github.com/open-telemetry/opentelemetry-specification/issues/3415) from https://opentelemetry.io/docs/reference/specification/protocol/otlp/ to https://github.com/open-telemetry/opentelemetry-proto/tree/main/specification/ (pending https://github.com/open-telemetry/opentelemetry-proto/pull/458).

We will need to update the documentation website appropriately (I am not sure how exactly it works today, so not sure what needs to change).

Note that only the following files are moving (not the entire directory):
```
specification/protocol/README.md
specification/protocol/design-goals.md
specification/protocol/otlp.md
specification/protocol/requirements.md
```

---

### Prep

- [x] #2676
- [x] #2677
  - [x] #2701
- [x] #2691
- [x] https://github.com/open-telemetry/opentelemetry-proto/pull/472
- [x] https://github.com/open-telemetry/opentelemetry-proto/pull/469

### Tasks

- [x] #2786
- [x] #2794
- [x] #2799
- [x] https://github.com/open-telemetry/opentelemetry-proto/pull/479
  - [ ] Add aliases to OTLP spec pages
- [x] #2839
- [x] #2846
- ~Run prettifier over OTLP spec pages~

**Comment by tigrannajaryan** [comment]
@open-telemetry/docs-approvers can you please help with this?

**Comment by svrnm** [comment]
@chalin can you give this a look? ty

**Comment by chalin** [comment]
So what is it that you would like to see on the website @tigrannajaryan and @open-telemetry/specs-approvers? 

**Two options** come to mind and are presented below. Let me know which you prefer, or whether you had something else in mind.

### 1. Publish the OTLP spec separately under "Reference"

Something like this:

> <img width="1054" alt="Screen Shot 2023-05-08 at 08 40 18" src="https://user-images.githubusercontent.com/4140793/236826440-cf33d5f5-77d9-4d3b-9c28-cd766ec5b0e0.png">

### 2. Publish the `opentelemetry-proto` repo OTLP spec through it's current location in the OTel spec ...

... that is, https://opentelemetry.io/docs/reference/specification/protocol/otlp/, as an **override** to any pages that the OTel spec might provide.

While this option is minimally disruptive, it _might_ lead to confusion if/once #2666 lands and the spec version is visible as part of the page title and breadcrumbs. That is, we might end up with something like this:

> <img width="668" alt="Screen Shot 2023-05-08 at 08 48 07" src="https://user-images.githubusercontent.com/4140793/236828396-6bb7455f-9db0-4389-ac45-cb615a2ed501.png">

**Comment by tigrannajaryan** [comment]
>1. Publish the OTLP spec separately under "Reference"

I prefer this.

**Comment by svrnm** [comment]
I would also prefer (1), looks more user-friendly

Option (1) also has the advantage that the "Reference >" top level item is not only having one child, which is kind of confusing.

We should also add a section on the Reference page that explains what people will find here and what the differences are (not everybody is aware what OTel/OTLP stands for and what the differences are)

**Comment by austinlparker** [comment]
voted 1

**Comment by cartermp** [comment]
1 for me as well

**Comment by chalin** [comment]
@tigrannajaryan and @open-telemetry/specs-approvers I have a question for you:

The OTLP spec pages link to `.proto` files. Where to you want these links to point to? I see 3 options:

(a) Host the proto files on the website (as static assets) and point to the website-local files
(b) Link to proto files in the OTLP repo @HEAD
(c) Link to proto files in the OTLP repo at a specific tagged release

While (b) is the simplest solution, there's the potential problem that the site's OTLP docs and the repo's `.proto` files might not correspond to the same version. By hosting the `.proto` files on the website (a), we guarantee that they sync.

Option (c) also guarantees that the docs and proto files remain in sync, but it implies that we would never be able (easily) host OTLP docs other than at a tagged release.

Thoughts?

**Comment by tigrannajaryan** [comment]
Both options (a) and (c) are fine with me. I think we only want to host tagged releases on the website. Anybody who is interested in the head can work directly with the [opentelemetry-proto](https://github.com/open-telemetry/opentelemetry-proto/) repo.

**Comment by chalin** [comment]
Thanks for the feedback @tigrannajaryan.

Can we make some progress on getting https://github.com/open-telemetry/opentelemetry-proto/pull/469 approved and merged? I'm waiting on that before I before I bring it in (though it's approved and the merge is delayed, I can implement the new directory structure in this repo, temporarily).
