### ISSUE TITLE
Adjust to move Semantic Conventions out of OTel spec

### ISSUE THREAD

**Issue by jsuereth** [open-telemetry/opentelemetry.io#2721]
As part of [OTEP #227](https://github.com/open-telemetry/oteps/blob/main/text/0227-separate-semantic-conventions.md) we're moving the semantic conventions out of the Specification and into a new repository.

As part of this:

- We're leaving the Markdown files for semconv in the specification repository with links to the new location warnings.
- Semantic Conventions will be released with their own version number from this repository: https://github.com/open-telemetry/semantic-conventions

We may be re-architecting the structure of this repository, but we can negotiate how best to do so for the website to easily pull it in.

---

### Tasks

- [x] #2785
- [x] #2918
- [x] #2907
- [x] #2982
- [x] #2987
- [x] https://github.com/open-telemetry/semantic-conventions/pull/170
- [x] Ensure every section has a README
  - [x] https://github.com/open-telemetry/semantic-conventions/pull/171
- [x] https://github.com/open-telemetry/semantic-conventions/pull/175
- [x] https://github.com/open-telemetry/semantic-conventions/pull/177
- [x] #2984
- [x] #2998
- [x] #3008
  - [x] #3010
- [x] https://github.com/open-telemetry/semantic-conventions/pull/187
- [x] Ensure that links to OTel spec from semconv pages refer to website pages (`/docs/specs/otel`)
  - [x] Waiting on https://github.com/open-telemetry/semantic-conventions/pull/185
  - [x] #3012
- [x] #3033
- [x] Ensure that links into semconv from other specs refer to website pages:
  - [x] #3037
- [x] Add semconv version to landing page title - #3033
- [x] Add version update to autoupdate script - #3033
- [x] Fix links in semconv pages, and drop workaround in this repo: `|(/resource/faas\.md)#function-as-a-service|$1|;` - https://github.com/open-telemetry/semantic-conventions/pull/180
- [x] Ensure "View page source" and other links are working, esp. for index files (originally README.md files)
- [x] Address:
  - [x] https://github.com/open-telemetry/opamp-spec/issues/150 -- until then, this causes a build warning; the warning is skipped by an entry in `.warnings-skip-list.txt`
  - [x] Drop skip pattern from `.warnings-skip-list.txt` (after #3026 is merged)

Other to-dos from #2908:

- [ ] Add semantic conventions to ToC / index
- [ ] Ensure semantic-conventions -> specification links are accurately internalized to the website
- [ ] Ensure specification -> semantic-conventions links are accurately internalized to the website.
- [ ] Remove `specification/semantic_conventions/*.md` from being pulled in OpenTelemetry specification.
- [ ] Figure out if supplementary guidelines belong on the website

**Comment by chalin** [comment]
Note that I've closed the following PR since the semconv pages have moved

- https://github.com/open-telemetry/opentelemetry-specification/pull/3498

**Comment by jsuereth** [comment]
@chalin Let me know how best we can start moving this issue forward.  Happy to have you at the semconv working group to explain what you need to us, *or* we can attend whatever SiG/WGs meetings you attend.

**Comment by chalin** [comment]
@jsuereth - I was OOO. Catching up now. I didn't have the time to work on this before I left. I see that you've submitted a PR. I'll take a look as soon as I can.

**Comment by chalin** [comment]
Oh, I remember that I had issues regarding the structure of the semconv repo docs. I'll write more about that soon.

**Comment by joaopgrassi** [comment]
Hi @chalin, I volunteered to take up this work on the semconv repo side. Let me know how we can best work together. I'm available on Slack as well.

**Comment by chalin** [comment]
@jsuereth - I see from the following that you'll be restructuring the spec:

- https://github.com/open-telemetry/semantic-conventions/issues/137

Do you want to wait for that restructuring to land before starting to publish the semconv spec on the website?

**Comment by chalin** [comment]
Hi @joaopgrassi @jsuereth: I see that part of the work has already been done in 

- #2908

My suggestion would be to bring in the changes incrementally and delay publishing anything to the production server until work on https://github.com/open-telemetry/semantic-conventions/issues/137 is complete. That way we can avoid having to introduce a bunch of redirect rules. WDYT?

**Comment by chalin** [comment]
In terms of bringing things in incrementally, here's a first PR:

- #2918

PTAL

**Comment by joaopgrassi** [comment]
> Do you want to wait for that restructuring to land before starting to publish the semconv spec on the website?

Yeah I think that would be best, to avoid double work. I will be helping out in the restructuring so should be "quick"

**Comment by chalin** [comment]
Questions from https://github.com/open-telemetry/opentelemetry.io/pull/2920#pullrequestreview-1503181544:

> * How do we get left-hand outline like the spec has for sections?

That will happen automatically once the semconv reorg lands.

> * Can we change all links to specification in semconv to point at the otel.io copy of the specification?

Yes. I didn't address this yet because the semconv pages currently link directly to v1.21.0 of the OTel spec, whereas the website is now hosting v1.22.0.

> * Can we change all links to semconv from the specification to point at the otel.io copy of the semconv?

Yes, once we're closer to publishing the new semconv spec, I can work on addressing this.

**Comment by joaopgrassi** [comment]
Hi @chalin the restructure is now done. How should we tackle the website work now?

**Comment by jsuereth** [comment]
@chalin We need to decide if we do that change in this release or not.

**Comment by jsuereth** [comment]
@chalin Do you think enough work has been done on the Semantic Convention repository that we could cut a release tag to continue the work on the website?  (Showing the version and bumping to the release version).

I'm assuming that's the case from your last PR, but wanted to confirm before we cut a release.

**Comment by chalin** [comment]
Hi @jsuereth - oh, I missed your request to sync last Friday because I ended early. I'm catching up on notifications now. I'd like to bring in the latest semconv, clean up the scripts and make sure that all is good. Cutting a release is seems reasonable.

**Comment by jsuereth** [comment]
The `v1.12.1` tag has been cut.

**Comment by jsuereth** [comment]
FYI - With this tag, we need to start serving the `1.21.0` file under the `schemas/` directory.

**Comment by chalin** [comment]
Does this mean that all schemas in that directory are to be served? If so, I'll submit a PR doing that now.

**Comment by chalin** [comment]
Does this also mean that we can publish the semconv pages to the production server?

**Comment by chalin** [comment]
@jsuereth - while there will be ongoing work to support semconv and other specs, can we close this issue considering that the bulk of the work has been done?

**Comment by chalin** [comment]
We're well beyond the original migration effort. Closing. Feel free to comment here if you'd like this to stay open.
