### ISSUE TITLE
[meta] Document Kubernetes Story

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry.io#3005]
**Desired feature or idea**: What would you like to see happen?

I would like to see a Kubernetes focused section of the docs site.

Kubernetes has become a big enough industry tool that the OpenTelemetry community as built many, many tools to facilitate monitoring k8s and things running on k8s.  Tools such as:

- [x] OTel Operator
- [ ] TargetAllocator
- [x] Helm Charts
  - [x] [Collector](https://github.com/open-telemetry/opentelemetry.io/pull/3049)
  - [x] [Operator](https://github.com/open-telemetry/opentelemetry.io/pull/3051)
  - [x] [Demo](https://github.com/open-telemetry/opentelemetry.io/pull/3055)
- [x] Collector components
  - [x] filelogrecevier
  - [x] k8sclusterreceviever
  - [x] k8sobjectsreceiver
  - [x] kubletstatsreceiver
  - [x] hostmetricsreceiver
  - [x] k8sattributesprocessor
  - [x] prometheusreceiver
- [x] Getting Started

Documentation for all these different tools exists, but there is no central location where a user interested in k8s and otel can go to learn.  I would like to add a large section to the site where were can document the k8s journey with OTel.  This section would contain stuff like:

- Otel Operator docs
- List of collector components useful in k8s
- helm chart documentation
- getting started journey
- troubleshooting guide

**Comment by TylerHelmuth** [comment]
If the community likes this idea I would like to start working on it.

**Comment by svrnm** [comment]
yes, let's do this. See @cartermp's comment on slack as well (highlights are mine):

> I am emphatically in favor of it, **replacing the top-level “k8s operator” node with “kuberneters”** and all the things that are relevant are underneath

Wondering if there should also be a link/document around otel in k8s itself https://kubernetes.io/docs/concepts/cluster-administration/system-traces/ ?

**Comment by svrnm** [comment]
cc @pavolloffay @kristinapathak @frzifus @yuriolisa FYI as well, maybe some of our KubeCon tutorial can be re-used here as well: https://github.com/pavolloffay/kubecon-eu-2023-opentelemetry-kubernetes-tutorial

**Comment by TylerHelmuth** [comment]
I will start working on this, please assign me

**Comment by svrnm** [comment]
@TylerHelmuth do you want to keep this ticket open for tracking further progress on the list above? We can turn this into a meta issue if so

**Comment by TylerHelmuth** [comment]
Yes

**Comment by svrnm** [comment]
OK, I updated your initial comment to track the tasks, double check what is done already and then we can close the other ones via follow up.

Thanks again for taking care of this, this is making a huge difference!

**Comment by TylerHelmuth** [comment]
I going to start work on the Collector pieces next.  I want to document all the important components, but I also want to document the 3 important deployment patters: sidecar, daemonset, and deployment.  There will likely be some overlap with https://opentelemetry.io/docs/collector/deployment/, but I want a hyper-specific kubernetes doc where we can talk about the specific components that a need specific deployment in k8s to function properly.  


Once that is done I think we'll have all the supporting documentation for an initial Getting Started, which will focus on getting users started with the collector in k8s.

At the moment I think I'll position the Getting Started flow with a focus on the helm chart since it has the concept of the presets to help get you started.  I want this section to focus on:
- getting a collector daemonset installed to collect application traces/metrics/logs, kubeletstats, and host metrics.
- getting a collector deployment installed to collector cluster metrics and events.

In a collector world in order to get all the data you need both installations so I want to focus on that.

**Comment by cartermp** [comment]
That all sounds very good.

**Comment by svrnm** [comment]
> There will likely be some overlap with [opentelemetry.io/docs/collector/deployment](https://opentelemetry.io/docs/collector/deployment/), but I want a hyper-specific kubernetes doc where we can talk about the specific components that a need specific deployment in k8s to function properly.

We can cross-link again or review the existing docs if some of that is k8s specific already and should be moved.

@mhausenblas FYI

**Comment by mhausenblas** [comment]
> We can cross-link again or review the existing docs if some of that is k8s specific already and should be moved.

Thanks and makes sense, yes @svrnm

**Comment by svrnm** [comment]
thanks for all this good progress here @TylerHelmuth 

Question: Do you think there is a place to link out to [Traces for Kubernetes System Components](https://kubernetes.io/docs/concepts/cluster-administration/system-traces/) ?

**Comment by TylerHelmuth** [comment]
Yes we should. Probably in the top level docs somewhere.

**Comment by TylerHelmuth** [comment]
I am going to improve the target allocator doc and then call this issue closed.  I know there were some other ideas called out, but I think those can be handled in separate issues - this issue's goal was to outline all the most important otel-specific pieces of k8s monitoring that needed documented.  Any improvements such as reorganizing or documenting native k8s-tracing can be added in the future.
