### ISSUE TITLE
Complete move of Marketing Guidelines to website from community repo

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#3079]
- Similar to #2947
- Currently, we have **duplicate sources** from two repos:
  - https://github.com/open-telemetry/opentelemetry.io/blob/main/content/en/community/marketing-guidelines.md, it was
    added via #2050
  - https://github.com/open-telemetry/community/blob/main/marketing-guidelines.md, 
    which is linked to from the footer of the OTel website
- Related: https://github.com/open-telemetry/opentelemetry.io/pull/3076#pullrequestreview-1546641726

/cc @trask @open-telemetry/governance-committee

## Tasks

- [x] Ensure that local Marketing Guidelines page is still up-to-date relative to the community repo page -- see the next comment below
- [x] Update the footer to refer to the website-local - #3088
- [x] ~Delete the community repo page, or~ refer it to the corresponding website page - https://github.com/open-telemetry/community/pull/1616

**Comment by chalin** [comment]
There are no significant differences between the two versions after running Prettier:

```diff
$ npm run _prettier:any -- content-modules/community/marketing-guidelines.md --write 
$ diff content-modules/community/marketing-guidelines.md content/en/community/marketing-guidelines.md 
1c1,5
< # OpenTelemetry Marketing Guidelines for Contributing Organizations
---
> ---
> title: OpenTelemetry Marketing Guidelines for Contributing Organizations
> linkTitle: Marketing Guidelines
> spelling: cSpell:ignore devstats
> ---
3c7
< OpenTelemetry (a.k.a. "OTel") is a collaboration among end-users, adjacent OSS
---
> OpenTelemetry (aka OTel) is a collaboration among end-users, adjacent OSS
85c89
<    email to cncf-opentelemetry-governance@lists.cncf.io and include an
---
>    email to <cncf-opentelemetry-governance@lists.cncf.io> and include an
```
