### ISSUE TITLE
Find a better way to use tabpane shortcodes

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#3127]
Part of the problem with the current way in which we're using tabbed panes is that the tools don't know that the content of a `tab` is code. Consequently we are forced to add checker and linter **directives** like `<!-- markdownlint-disable -->`, `<!-- prettier-ignore-start -->`, etc., for each checker and linter.

I propose that we use code-block fences inside tabs. Here's an illustration of what I mean:

- #3126

### Tasks

- [x] POC: #3126
- [x] Prep: #3128
- [x] Convert all tabpanes - #3137
- [x] Upstream style changes to Docsy - https://github.com/google/docsy/pull/1671
- [ ] Update docsy and drop our local workarounds
