### ISSUE TITLE
Update Font Awesome for New "X" Logo

### ISSUE THREAD

**Issue by nmummau** [open-telemetry/opentelemetry.io#3647]
**Issue:** The website "Twitter" has been renamed to "X," and we need to update our web assets accordingly.

**Background:** As part of this change, we will be updating the URLs and icons that previously pointed to the "Twitter" logo to now use the new "X" logo.

**Prerequisite:** A prerequisite if this issue being worked will be for `@fortawesome/fontawesome-free` to be updated in [google/docsy](https://github.com/google/docsy) and then the [cncf/docsys](https://github.com/google/docsy) fork is updated. 
See [Pull Request](https://github.com/google/docsy/pull/1765)

## Proposed Changes

1. **Update URLs:** We will update all references to the "Twitter" website URL to point to the new "X" website URL.
2. **Update Icons:** We will update the icons that were previously associated with "Twitter" to now display the new "X" logo.
3. **Upgrade Font Awesome:** To accomplish the icon update, we need to upgrade our Font Awesome library to include the new "X" logo icon. The icon to use should be [can be seen here](https://fontawesome.com/icons/x-twitter?f=brands&s=solid)

## Tasks

- [ ] Update all references to "Twitter" to use the new "X" URL.
- [ ] Replace all "Twitter" icons with the new "X" logo using Font Awesome.
- [ ] Upgrade Font Awesome to latest.

**Comment by chalin** [comment]
Thanks, I can understand some of the eagerness to make Twitter-related updates, but I'd like to separate issues:

1. Updating the **logo**, to use the new X logo. The proper way to do this in the context of this repo is to **wait for the Docsy** update that will include https://github.com/google/docsy/pull/1754. Then we bring in that change via Docsy
2. Replacing twitter.com by x.com

Regarding (2), I think that it's **premature** to change hosts, since X.com redirects to twitter.com:

```console
$ curl -sI https://x.com                    
HTTP/2 302 
date: Wed, 06 Dec 2023 00:44:13 GMT
location: https://twitter.com/
...
```

Until twitter.com is officially a redirect, I'd keep our references to twitter.com.

My 2 cents. @open-telemetry/docs-maintainers WDYT?

**Comment by austinlparker** [comment]
Honestly given the way that website is going I'm not sure it's worth putting any effort into supporting it. Do we even get any traffic/shares out to Twitter?

**Comment by chalin** [comment]
Very a good point @austinlparker!

**Comment by svrnm** [comment]
For 1, I think we all agree that we can replace the bird logo with the X logo whenever the font awesome update lands in docsy. We then can also make the link swap (twitter.com -> x.com)

For 2 (updating the URLs), take a look at the initial commit from @nmummau's PR: https://github.com/open-telemetry/opentelemetry.io/pull/3649/commits/71bfbf8742932358ee84b5492f087a7ad5e0609d -- ALL links to twitter, except the one in the page footer, are in blog posts. As I said over there as well is that we should treat blog posts as historical and not update those links (we can make an exception for everything post Jul 23 when twitter was officially renamed to X). In that context to your point, @nmummau, around the possibility that twitter.com might be sunsetted and be broken: I can live with that, we can add a note to the blog posts then letting people now that they are historical and that's it. 

For future links, we can make sure that people use x.com accordingly, but honestly I think we will see a lot less of them, because you need an account to access that content, so people will probably prefer linking to different places (fediverse, github, ...) to stay open & accessible.

@chalin (not urgent, we can discuss when you're back): I remember that we talked about adding a banner to old blog posts in the past already (like k8s is doing it, e.g. [here](https://kubernetes.io/blog/2016/12/kubernetes-supports-openapi/), do we have an issue for that already?

**Comment by chalin** [comment]
Here's the update of Docsy (and FA):

- #3666

Btw, I didn't want to modify your issue's opening-comment text, so I created a separate one for tracking each of the aspects of the update:

- #3665

**Comment by svrnm** [comment]
fixed
