### ISSUE TITLE
Twitter-to-X updates

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#3665]
As a **meta question** to this issue is: do we still want to link to the OTel Twitter/X account? If so, then this issue is a generalization of:

- #3647

## Prerequisite / cleanup

- [x] #3653
- [x] Docsy: update to `v0.8.0-6-g6a71096` - #3666

## Tasks

- [x] Use the X logo --> maybe via #3649?
- [x] Replace "Twitter" by "X" or "X, formerly Twitter" -- probably wait for the previous item to happen
- [ ] Replace references to  https://twitter.com by  https://x.com, probably only after X stops redirecting to twitter.com:
  ```console
  $ curl -sI https://x.com                                             
  HTTP/2 302 
  date: Fri, 08 Dec 2023 22:35:34 GMT
  location: https://twitter.com/
  ...
  ```

---

Related:

- #3647

**Comment by svrnm** [comment]
> Replace references to [twitter.com](https://twitter.com/) by [x.com](https://x.com/), probably only after X stops redirecting to twitter.com

If I see things correctly after #3649 gets merged the remaining references live in old blog posts, where we will never apply a change (I am OK with those links being dead eventually)

> Replace "Twitter" by "X" or "X, formerly Twitter" -- probably wait for the previous item to happen

"X, formerly Twitter" is my preference, makes searching for it much easier as well

**Comment by chalin** [comment]
So are we all done here, @svrnm?

**Comment by svrnm** [comment]
@chalin I would say so, yes.
