### ISSUE TITLE
[CI] Ensure that build failures are reported to an OTel Slack channel

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#3736]
### Tasks

- [x] https://cncfservicedesk.atlassian.net/browse/CNCFSD-2133 - @RobertKielty
- [x] Create a channel to be used as a target for Netlify build errors:
  - [x] ~Create private channel `#otel-comms-approvers`, private: https://cloud-native.slack.com/archives/C06EDFPQ5EH~ Oops, Netlify can't access private channels.
  - [x] Create **public** channel `#otel-comms-netlify-msgs`, 
    see https://cloud-native.slack.com/archives/C06G9AD6JAH
- [x] Configure the Netlify-Slack integration to set notification for production build errors (only), see
  https://app.netlify.com/sites/opentelemetry/configuration/notifications

### Context and info

- #3707
- https://cloud-native.slack.com/archives/C040BF9TG9J/p1704747022261149
  > ~#otel-comms-maintainers~ --> opting for `#otel-comms-approvers`
  > private
- https://cloud-native.slack.com/archives/C040BF9TG9J/p1703260261365759
- https://docs.netlify.com/integrations/slack-app/
- Config panel: https://app.netlify.com/sites/opentelemetry/configuration/notifications

**Comment by chalin** [comment]
I don't have the required permissions, but I've escalated the request.

**Comment by austinlparker** [comment]
Opened a service desk ticket https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-2133?created=true

**Comment by chalin** [comment]
All done. We'll have to wait for a production build error to see if/how this works :). Closing for now.
