### ISSUE TITLE
Public Google Analytics Dashboard

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#4017]
@open-telemetry/docs-cn-maintainers et al.: is there any interest in publicly accessible GA4 dashboard? I recall that a while back @caniszczyk was eager for this.

@a-mccarthy has done a fantastic job a creating a [Looker Studio](https://lookerstudio.google.com) template that we should be able to use for OTel analtyics: https://lookerstudio.google.com/u/0/reporting/df34ae1f-5ce4-452f-9f3d-87dc50273dd2/page/4VDGB/edit

Reference:

- https://github.com/cncf/techdocs/issues/105#issuecomment-1946309020

### Tasks

- [x] Create publish dashboard - https://lookerstudio.google.com/s/tLbbZAtvcjk
- [x] Ensure that a generic OTel account has access to the dashboard as an editor
  - [x] [Per @austinlparker's suggestion](https://cloud-native.slack.com/archives/C06EDFPQ5EH/p1709756098971789?thread_ts=1709755238.477249&cid=C06EDFPQ5EH), invited the OTel admin as editor
  - [x] Access granted, and confirmed by @austinlparker 
- [x] Add a link to the dashboard somewhere on the site: 
  #4102

**Comment by cartermp** [comment]
I would love something public. For now I just rely on the honeycomb sandbox page: https://play.honeycomb.io/opentelemetry-web/datasets/opentelemetry.io/result/fb9jVfaCt3u?useStackedGraphs

**Comment by svrnm** [comment]
Yes, having something public would be great. Gives people also more confidence on what we do with the data collected.

Just thinking three steps ahead, if we add this at some point on the website, we can also add the honeycomb sandbox there and then let people know that we can send them those traces as well (under some restrictions that we apply, so that we do not have 50+ vendors)

**Comment by cartermp** [comment]
Yeah, the Honeycomb thing should probably be repeatable in theory, the main thing is the vendor would probably need to have a free (and sign-in free) publicly accessible view.

**Comment by chalin** [comment]
All, PTAL at our shinny new public analytics dashboard:

- https://lookerstudio.google.com/reporting/34c2a65a-39e8-44aa-afa0-094975fee55d

Thanks again to @a-mccarthy for helping out, and the starter template!

@open-telemetry/docs-approvers: is this good enough as a first cut to publish, and add a link to from OTel.io? If so, where shall we add the link? In the footer (which also shows up in the [community page](https://opentelemetry.io/community/)) as **Site analytics**?

**Comment by cartermp** [comment]
Yes, this is good enough to publish, and let's get some links up.

**Comment by chalin** [comment]
All done!
