### ISSUE TITLE
[IA] Relocate Java Automatic pages to new Zero-code section + other page rework

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#4428]
Contributes to the following for Java:

- #4427

### Tasks

- [x] Minimal changes, "just" relocate pages
- [x] Canonicalize all links (drop temporary link-checker rule) - #4565
- [x] Ensure that dynamic front-matter parameters get auto-updated too in `content/en/docs/zero-code/java/_index.md` -
  #4569
- [x] Adjust CODEOWNERS
- [x] Page-relative aliases in the Java agent pages need to be fixed too. Those page-relative aliases made sense in the context of the old paths (find out when those aliases where added and hard-code the old paths in replacement of "..") -
  #4568
- ~Add a placeholder under the old SDK Java section redirecting to the new Automatic section?~

@svrnm @zeitlinger - let's use this issue to track all the reorg and page additions

**Comment by chalin** [comment]
All done, closing.
