### ISSUE TITLE
Add Japanese version of website pages

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#4592]
- [x] #4580 - adds the `ja` site landing page
- [x] #4606
- [x] #4616
- [x] Create appropriate org-level groups
  - [x] https://github.com/open-telemetry/community/issues/2138
  - Cf. #4465
- [x] Update CODEOWNERS
  - Cf. also #4465 and the PRs used to close it
- [x] #4687

### References, previous art, etc:

- #4467
- #2402

/cc @ymotongpoo

**Comment by chalin** [comment]
@ymotongpoo @katzchang - note the addition of the **Specs** section under `/ja/docs` via:

- #4687

That **Specs** page is actually just a **redirect to the English Specs** section (hence the arrow icon next to the section name).

**Comment by ymotongpoo** [comment]
@chalin thanks for the update. I confirmed the URL of specs pages in Japanese was redirected to the original English version as no Japanese page exists yet.

**Comment by chalin** [comment]
@open-telemetry/docs-ja-approvers - Closing. Comment here if you feel that there is more core work to be done in the context of this issue — beyond just adding more content.
