### ISSUE TITLE
Add Portuguese version of website pages

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#4834]
We'll use this issue to track the added support of a `pt` (`pt-BR`) localization. This issue can be modelled after the following issue, without being identical since, for example, we might not be using CODEOWNERS for very long:

- #4592

I'll let other @open-telemetry/docs-maintainers or approvers populate this issue. I just wanted it created so that we have something to reference. A preliminary list of tasks is provided below.

### Tasks

- [x] Create homepage - #4794
- [x] Create org-level groups for `pt` maintainers and approvers.
  - @edsoncelio - you'll want to identify / list maintainers and approvers
  - Cf. https://github.com/open-telemetry/community/issues/2232
- [x] Create an issue label for `lang:pt`
- [ ] Update CODEOWNERS or the equivalent
- [ ] Other content:
  - [x] #4868
  - [ ] For more entries, see #4922

**Comment by edsoncelio** [comment]
Hi @chalin! 

A few questions related to the next steps after the index page localization.
 
 - Regarding the maintainers, all need to be part of the open telemetry org, right?  A few folks want to be part of it, but in a positive answer, we will need to work on it separately.
 - Following the [Japanese setup](https://github.com/open-telemetry/opentelemetry.io/issues/4592), my suggestion is to start with the localization for the pages "What's OpenTelemetry" and "Getting Started."  Does this need to be done only after the maintainers are set up, or can we already start to work on it?
 
 Thanks!

**Comment by svrnm** [comment]
hey @edsoncelio,

I will raise the issue to get the groups created, to bootstrap the group we will add people initially who are members of the org already. For those who are not members of the org, they can still review and we will count them in the early days and merge when they did so, after a while we can add them to the org (and teams) as well.

You can go ahead and create localizations independently of that group existing, those 2 things can be managed async.

Thanks,
Severin

**Comment by chalin** [comment]
@theletterf @svrnm - I think that this can be closed, right?

**Comment by theletterf** [comment]
Fine by me!
