### ISSUE TITLE
Add Spanish (`es`) version of website pages

### ISSUE THREAD

**Issue by krol3** [open-telemetry/opentelemetry.io#4887]
Following the samples of [Japanese](https://github.com/open-telemetry/opentelemetry.io/issues/4592) and [Portuguese](https://github.com/open-telemetry/opentelemetry.io/issues/4834) version of websites. We would like to support the Spanish website page and translations for the docs.

We'll use this issue to track the added support of a sp (Spanis) localization. 

**Tasks**

- [x] Figure out which Spanish variety we are going to use (es_ES?, edited by @svrnm)
- [x] Create homepage - [es] Localize index page to Spanish:
  - #4989
  - #5005
- [x] Create an issue label for `lang:es`
- [x]  Create org-level groups for `es` maintainers and approvers:
  - @krol3 - you'll want to identify / list maintainers and approvers
  - @open-telemetry/docs-approvers will follow through and create the appropriate request for the group creation:
     https://github.com/open-telemetry/community/issues/2262
- [x]  Update code/component owners 
- [x] Other pages (can be done outside of the scope of this issue):
  - [x] Add Spanish translation for "What is OpenTelemetry" - https://github.com/open-telemetry/opentelemetry.io/pull/5021
  - [x] https://opentelemetry.io/ - [es] Localize index page - https://github.com/open-telemetry/opentelemetry.io/pull/4989
  - [x]  https://opentelemetry.io/docs/demo/ - https://github.com/open-telemetry/opentelemetry.io/pull/5053
  - [x]  https://opentelemetry.io/docs/getting-started/ - https://github.com/open-telemetry/opentelemetry.io/pull/5054
  - [x] https://opentelemetry.io/docs/kubernetes/ - https://github.com/open-telemetry/opentelemetry.io/pull/5055
  - [x]  https://opentelemetry.io/docs/concepts/ - https://github.com/open-telemetry/opentelemetry.io/pull/5057
  - [x] https://opentelemetry.io/docs/contributing/ - https://github.com/open-telemetry/opentelemetry.io/pull/5058

**References**

- [Site localization](https://opentelemetry.io/docs/contributing/localization/)
- [Improved i18n support](https://github.com/open-telemetry/opentelemetry.io/issues/4467)

cc: @chalin

**Comment by svrnm** [comment]
@krol3 @theletterf based on a discussion during the SIG meeting I updated the issue description, that as a first step we need to agree on the Spanish Variety

**Comment by chalin** [comment]
As discuss during the (end of the) Comms meeting: which ever Spanish regional variant @krol3 et al. decide upon, that will become _the_ defacto/default region for the OTel docs. We'll eventually need to choose a language code (see below for choices), but regardless, the `content` subfolder will be `es`.

Here are some of the most commonly used Spanish language codes that start with `es-`:

- es-ES: Spanish (Spain)
- es-MX: Spanish (Mexico)
- es-AR: Spanish (Argentina)
- es-CO: Spanish (Colombia)
- es-PE: Spanish (Peru)
- es-VE: Spanish (Venezuela)
- es-CL: Spanish (Chile)
- es-419: Spanish (Latin America and the Caribbean)

Maybe either `es-419` or `es-ES`, WDYT?

**Comment by krol3** [comment]
> As discuss during the (end of the) Comms meeting: which ever Spanish regional variant @krol3 et al. decide upon, that will become _the_ defacto/default region for the OTel docs. We'll eventually need to choose a language code (see below for choices), but regardless, the `content` subfolder will be `es`.
> 
> Here are some of the most commonly used Spanish language codes that start with `es-`:
> 
> * es-ES: Spanish (Spain)
> * es-MX: Spanish (Mexico)
> * es-AR: Spanish (Argentina)
> * es-CO: Spanish (Colombia)
> * es-PE: Spanish (Peru)
> * es-VE: Spanish (Venezuela)
> * es-CL: Spanish (Chile)
> * es-419: Spanish (Latin America and the Caribbean)
> 
> Maybe either `es-419` or `es-ES`, WDYT?

Following the kubernetes documentation spanish translation, we don't use a local/region/country variant in spanish. We collaborate with each other to translate to spanish (es).

**Comment by theletterf** [comment]
@krol3 For the priority pages, I was thinking of the same list as pt-BR, plus perhaps the contribution guide. What do you think?  https://github.com/open-telemetry/opentelemetry.io/issues/4922

**Comment by svrnm** [comment]
@theletterf based on our conversation on Monday, I was under the assumption that while we are going to use `es` we still need to agree on the defacto variant that we use (similar to what we do with pt and zh).

**Comment by theletterf** [comment]
@svrnm I've no strong feelings about it at this stage. I'd go with `es-ES`, but I'm guessing here that K8s chose to go with just `es` to foster contributions and avoid conflicts with lexical variants. FWIW, their site reads as `es-ES`; I doubt regional vocabulary from all around the Hispanosphere will ever make it to the docs — and we'll edit it if it does.

**Comment by theletterf** [comment]
`lang:es` label created.

**Comment by theletterf** [comment]
Opened https://github.com/open-telemetry/community/issues/2262

**Comment by theletterf** [comment]
Created #4989

**Comment by krol3** [comment]
> Hey @krol3,
> 
> thank you for raising this issue! Having a spanish translation of the OpenTelemetry website is something we are looking forward to have, so thanks for offering your help!
> 
> Localization & Internationalization is still a new topic to use, so we are at the moment intentionally slowing down the onboarding for new languages, to avoid overburdening maintainers and to avoid you having a bad experience. I say this upfront because it may take a few weeks until we can successfully add a new language.
> 
> Saying all that, here are the next steps:
> 
> * Find at least 1 more (ideally 2) people that are willing to help with the translation, such that someone who does the translation always has a person that can do the review.
> * Create a PR for the homepage (and nothing more), following the example of other languages, e.g. [pt](https://github.com/open-telemetry/opentelemetry.io/pull/4794). Leave editing the `hugo.yml` to us, we will update your PR accordingly
> * Wait for this PR to be merged (this is where we might put a delay)
> * We will after the PR has been merged setup the rest of the language (adding labels, groups, etc.)

Hi @svrnm , I would like to propose to help in the Spanish translations to @electrocucaracha, @ramrodo. They're contributors and maintainers in the k8s website. I know more people will be interesting to help too.

**Comment by krol3** [comment]
> Here are some of the most commonly used Spanish language codes that start with `es-`:
> 
> * es-ES: Spanish (Spain)
> * es-MX: Spanish (Mexico)
> * es-AR: Spanish (Argentina)
> * es-CO: Spanish (Colombia)
> * es-PE: Spanish (Peru)
> * es-VE: Spanish (Venezuela)
> * es-CL: Spanish (Chile)
> * es-419: Spanish (Latin America and the Caribbean)
> 
> Maybe either `es-419` or `es-ES`, WDYT?

hi @theletterf  yeah I will prefer just "ES" for the code spanish language, and don't use the region or country. For example in the kubernetes spanish documentation we use "ES". The contributors are from Guatemala, El Savaldor, Peru, Mexico, etc. We all colaborate to the ES language.

**Comment by ramrodo** [comment]
I agree with @krol3 , at the official Kubernetes documentation we use `es` to avoid region word conflicts and variants. The `es` dictionary is valid and available at **cspell**:

https://github.com/streetsidesoftware/cspell/blame/main/packages/cspell-trie-lib/src/lib/models/locale/knownLocales.ts#L197

**Comment by chalin** [comment]
Thanks @ramrodo for the reference into the cSpell code. IMHO, that says that `es` is recognized as a valid language code, but that doesn't give us an `es` dictionary. I'm not aware of an `es` dictionary, only an `es-ES` one via:

- https://github.com/streetsidesoftware/cspell-dicts
- Specifically, https://github.com/streetsidesoftware/cspell-dicts/tree/main/dictionaries/es_ES#readme

In summary, we can adopt `es` as the language code used as the folder name below `content`, but if we enable spell checking, then either you'll need to supply a "generic" `es` dictionary, or we'll go with the [es_ES](https://github.com/streetsidesoftware/cspell-dicts/tree/main/dictionaries/es_ES) one.

**Comment by theletterf** [comment]
@svrnm Could component owners be updated without waiting for the OTel community issue to be solved?

**Comment by svrnm** [comment]
> @svrnm Could component owners be updated without waiting for the OTel community issue to be solved?

Without the team being in place the process would run into an error everytime it runs. I am annoying people already to create the teams.

**Comment by theletterf** [comment]
@krol3 All initial actions completed. I'd close this task and follow with PRs.
