### ISSUE TITLE
[pt] Portuguese page localization

### ISSUE THREAD

**Issue by edsoncelio** [open-telemetry/opentelemetry.io#4922]
This issue is to track the pages to be localized in Portuguese.
Below, you can check the list of the pages we recommend localizing.

## Priority Pages
- [x] https://opentelemetry.io/ - https://github.com/open-telemetry/opentelemetry.io/pull/4794
- [x] https://opentelemetry.io/docs/what-is-opentelemetry/ - https://github.com/open-telemetry/opentelemetry.io/pull/4896
- [x] https://opentelemetry.io/docs/getting-started/ - https://github.com/open-telemetry/opentelemetry.io/pull/4980
- [x] https://opentelemetry.io/docs/getting-started/dev/ - https://github.com/open-telemetry/opentelemetry.io/pull/4980
- [x] https://opentelemetry.io/docs/getting-started/ops/ - https://github.com/open-telemetry/opentelemetry.io/pull/4980
- [x] https://opentelemetry.io/docs/concepts/ - https://github.com/open-telemetry/opentelemetry.io/pull/4901
- [x] https://opentelemetry.io/docs/concepts/observability-primer/ - https://github.com/open-telemetry/opentelemetry.io/pull/4997
- [x] https://opentelemetry.io/docs/concepts/context-propagation/ - https://github.com/open-telemetry/opentelemetry.io/pull/4984
- [x] https://opentelemetry.io/docs/concepts/signals/traces/ - https://github.com/open-telemetry/opentelemetry.io/pull/5019
- [x] https://opentelemetry.io/docs/concepts/signals/logs/ - https://github.com/open-telemetry/opentelemetry.io/pull/5062
- [x] https://opentelemetry.io/docs/concepts/instrumentation/code-based/ - https://github.com/open-telemetry/opentelemetry.io/pull/5093
- [x] https://opentelemetry.io/docs/concepts/semantic-conventions/ - https://github.com/open-telemetry/opentelemetry.io/pull/5047
- [x] https://opentelemetry.io/docs/concepts/signals/metrics/ - https://github.com/open-telemetry/opentelemetry.io/pull/5120
- [x] https://opentelemetry.io/docs/concepts/sampling/ - https://github.com/open-telemetry/opentelemetry.io/pull/5138
- [x] https://opentelemetry.io/docs/concepts/distributions/ - https://github.com/open-telemetry/opentelemetry.io/pull/5125
- [x] https://opentelemetry.io/docs/concepts/instrumentation/zero-code/ - https://github.com/open-telemetry/opentelemetry.io/pull/5201
- [x] https://opentelemetry.io/docs/concepts/signals/ - https://github.com/open-telemetry/opentelemetry.io/pull/4993
- [x] https://opentelemetry.io/docs/concepts/glossary/ - https://github.com/open-telemetry/opentelemetry.io/pull/5183
- [x] https://opentelemetry.io/docs/concepts/resources/ - https://github.com/open-telemetry/opentelemetry.io/pull/5132
- [x] https://opentelemetry.io/docs/concepts/signals/baggage/ - https://github.com/open-telemetry/opentelemetry.io/pull/5188
- [x] https://opentelemetry.io/docs/concepts/instrumentation/libraries/ - https://github.com/open-telemetry/opentelemetry.io/pull/5146
- [ ] https://opentelemetry.io/docs/concepts/instrumentation-scope/ 
- [x] https://opentelemetry.io/docs/concepts/instrumentation/ - https://github.com/open-telemetry/opentelemetry.io/pull/5287
- [x] https://opentelemetry.io/docs/concepts/components/ - https://github.com/open-telemetry/opentelemetry.io/pull/5396

Pages related to the announcement of the localization teams 
- [x] https://github.com/open-telemetry/opentelemetry.io/pull/4996/files#diff-0125ee13fe4e531c3ba9a4f0d1172669532897bc5840043064d40cf1899639b3 - https://github.com/open-telemetry/opentelemetry.io/pull/5035
- [x] https://github.com/open-telemetry/opentelemetry.io/pull/4996/files#diff-d63d56bdfd663201d05ecd3f6c89a35cb1a8b33f668d061e7192e5041678b2f0 - https://github.com/open-telemetry/opentelemetry.io/pull/5035

## How To Contribute
1. Look at [this guide](https://edsoncelio.dev/otel-localization-ptbr-guide/) to familiarize yourself with the contribution process.
2. Comment on this issue about which page you want to localize.
3. If you have any questions, let us know at [#otel-localization-ptbr](https://cloud-native.slack.com/archives/C076LET8YSK).

**Comment by EzzioMoreira** [comment]
Puxando a localização:
- https://opentelemetry.io/docs/concepts/context-propagation/

**Comment by leandrocarpenter** [comment]
Puxando a localização:

* [https://opentelemetry.io/docs/concepts/signals/](https://opentelemetry.io/docs/concepts/signals/)

**Comment by EzzioMoreira** [comment]
Puxando a localização `traces`: 

- https://opentelemetry.io/docs/concepts/signals/traces/

**Comment by icarotruta** [comment]
Irei puxar essa aqui:
https://opentelemetry.io/docs/concepts/components/

**Comment by marcelobaptista** [comment]
Puxando `instrumentation`

 [https://opentelemetry.io/docs/concepts/instrumentation/](https://opentelemetry.io/docs/concepts/instrumentation/)

**Comment by cassioliveiram** [comment]
Vou iniciar no `metrics`

https://opentelemetry.io/docs/concepts/signals/metrics/

**Comment by EzzioMoreira** [comment]
Vou puxar a localização do sinal: logs
- https://opentelemetry.io/docs/concepts/signals/logs/

**Comment by igorestevanjasinski** [comment]
Vou iniciar:
https://opentelemetry.io/docs/concepts/semantic-conventions/

**Comment by pedroespindula** [comment]
Trabalhando na localização do anúncio: https://github.com/open-telemetry/opentelemetry.io/pull/4996/files

**Comment by EdiltonOliveira** [comment]
Puxando a localização:  `glossary`.
 https://opentelemetry.io/docs/concepts/glossary/

**Comment by marcusteixeira** [comment]
Puxando `zero code`
https://opentelemetry.io/docs/concepts/instrumentation/zero-code/

**Comment by janssenlima** [comment]
Puxando `code-based`
https://opentelemetry.io/docs/concepts/instrumentation/code-based/

**Comment by EzzioMoreira** [comment]
Puxando `libraries`
https://opentelemetry.io/docs/concepts/instrumentation/libraries/

**Comment by janssenlima** [comment]
> Puxando `libraries` https://opentelemetry.io/docs/concepts/instrumentation/libraries/

@EzzioMoreira, o @marcelobaptista já fez no -> https://github.com/open-telemetry/opentelemetry.io/pull/5098/files

**Comment by janssenlima** [comment]
Puxando `resources` https://opentelemetry.io/docs/concepts/resources/

**Comment by lopes-felipe** [comment]
Vou puxar `sampling`
https://opentelemetry.io/docs/concepts/sampling/

**Comment by vitorvasc** [comment]
> Vou iniciar no `metrics`
> 
> https://opentelemetry.io/docs/concepts/signals/metrics/

@cassioliveiram Acabei de ver o seu comentário logo após abrir o PR (https://github.com/open-telemetry/opentelemetry.io/pull/5120) com a tradução deste item que havia comentado. Sorry! 

Caso tenha o PR ou já tenha feito algo, me avise! Podemos nos juntar para fazer em um mesmo PR.

**Comment by vitorvasc** [comment]
Puxarei essa:

https://opentelemetry.io/docs/concepts/distributions/

**Comment by genivaldosilva** [comment]
Olá, pessoal!

Não sei se aqui é o melhor local para isso, caso não seja, me avisem que ajusto.

Percebi que ao navegar na página (https://opentelemetry.io/pt/docs/what-is-opentelemetry/) e clicar no link de `começando` é redirecionado para a página em inglês, segue print da evidência:

![Screenshot from 2024-08-29 16-31-08](https://github.com/user-attachments/assets/cfccd419-754e-4757-9b2a-0eb76154bf33)

Acredito que seja so adicionar o `pt` aos links. Por exemplo: `/docs/getting-started/` => `/pt/docs/getting-started/`

Outro ponto é sobre o `pt`, não corre o risco de ser confundido com Português de Portugal?
Geralmente o que vemos é: `pt_BR` para Portguês do Brasil.

**Comment by edsoncelio** [comment]
> genivaldosilva

Olá @genivaldosilva, 

1. Mantemos as discussões no canal do slack da CNCF, tem certinho as informações do canal na descrição da issue, fica o convite para entrar no canal.
2. Sim, quando localizamos essa página inicial ainda não existiam as outras páginas em português, no futuro com certeza esses links devem ser atualizados, obrigado por apontar.
3. Sobre o código de idioma, antes de começar, tivemos algumas discussões sobre isso, então está correto, assim como o pt-BR é para Brazil para Portugal é pt-PT.

**Comment by cassioliveiram** [comment]
> > Vou iniciar no `metrics`
> > https://opentelemetry.io/docs/concepts/signals/metrics/
> 
> @cassioliveiram Acabei de ver o seu comentário logo após abrir o PR (#5120) com a tradução deste item que havia comentado. Sorry!
> 
> Caso tenha o PR ou já tenha feito algo, me avise! Podemos nos juntar para fazer em um mesmo PR.

@vitorvasc Também fiquei ausente e não tinha visto teu comentário aqui, então, tua PR ja está sendo revisada, tal hora posso fechar a minha pra nao ficar duplicado.

**Comment by EdiltonOliveira** [comment]
> Olá @icarotruta, @marcusteixeira , @EdiltonOliveira, estão precisando de ajuda com as páginas que estão trabalhando? Caso não consigam fazer agora (é totalmente normal acontecer, não se preocupem!) podem comentar aqui pra liberarmos pra outra pessoa fazer?

Olá, @edsoncelio ! Peço desculpas pela ausência. De fato, tentei fazer as contribuições, mas ocorrem imprevistos que me impediram de continuar. Pode liberar a minha task. Espero poder contribuir em outras oportunidades. Abraço.

**Comment by vitorvasc** [comment]
Bom dia!

@EdiltonOliveira @edsoncelio então puxarei o que estava com o Edilton, ok!?

https://opentelemetry.io/docs/concepts/glossary/

Abraços.

**Comment by edsoncelio** [comment]
> Bom dia!
> 
> @EdiltonOliveira @edsoncelio então puxarei o que estava com o Edilton, ok!?
> 
> https://opentelemetry.io/docs/concepts/glossary/
> 
> Abraços.

Valeu @vitorvasc!

**Comment by edsoncelio** [comment]
> Olá @icarotruta, @marcusteixeira , @EdiltonOliveira, estão precisando de ajuda com as páginas que estão trabalhando? Caso não consigam fazer agora (é totalmente normal acontecer, não se preocupem!) podem comentar aqui pra liberarmos pra outra pessoa fazer?

Tópicos liberados.

**Comment by EzzioMoreira** [comment]
Conversei com @marcusteixeira vou puxar:  https://opentelemetry.io/docs/concepts/instrumentation/zero-code/

**Comment by Lindemberg-Chagas** [comment]
puxando 
https://opentelemetry.io/docs/concepts/components/

**Comment by vitorvasc** [comment]
Puxando /languages/go: https://opentelemetry.io/docs/languages/go/

**Comment by Lindemberg-Chagas** [comment]
puxando 
https://github.com/open-telemetry/opentelemetry.io/pull/4896

**Comment by edsoncelio** [comment]
@cassioliveiram, pode me confirmar se ainda vai trabalhar na página https://opentelemetry.io/docs/concepts/instrumentation-scope/?
Caso contrário, pode avisar aqui, dai liberamos pra outra pessoa!

**Comment by edsoncelio** [comment]
⚠️⚠️⚠️
Essa issue está congelada, está aberta ainda porque temos 2 tópicos em abertos, mas para novas atividades seguiremos o novo fluxo alinhado no canal do slack (issue + PR), obrigado!
⚠️⚠️⚠️

**Comment by cassioliveiram** [comment]
> @cassioliveiram, pode me confirmar se ainda vai trabalhar na página https://opentelemetry.io/docs/concepts/instrumentation-scope/? Caso contrário, pode avisar aqui, dai liberamos pra outra pessoa!

Hey @edsoncelio Sim, gostaria, mas so consigo iniciar em um dia ou dois - se tiver alguem ja pronto, pode trocar sim.
Thanks e sorry a demora.

**Comment by vitorvasc** [comment]
Sobre a que falta para concepts/instrumentation-scope, deixo o PR:

https://opentelemetry.io/docs/concepts/instrumentation-scope/ -> https://github.com/open-telemetry/opentelemetry.io/pull/5604
