### ISSUE TITLE
Upgrade to Hugo 0.134+ -- possible breaking changes

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#5153]
Note that we might be impacted by breaking changes. For release notes, see:

- https://github.com/gohugoio/hugo/releases/tag/v0.134.0

### Tasks

- [x] #5265
- [x] https://github.com/gohugoio/hugo/issues/12886
- [x] https://github.com/gohugoio/hugo/pull/12901
- [ ] Upgrade to Hugo

**Comment by svrnm** [comment]
I quickly reviewed those changes, the only one that looks like we _might_ be impacted are the alerts?

**Comment by chalin** [comment]
There _might_ be an interplay with Docsy and Content summaries, given that they are now only processed as HTML. Something I'll be looking into on the Docsy side first, and then ensure that all is well here too (FYI).

**Comment by chalin** [comment]
I can confirm that the value of the `description` attribute or element in the generated page headers changes. In some cases we actually get extra leading blanks. I'd suggest that we just ignore that for now.

Maybe more significant is the following issue, which I'll wait to get feedback on before upgrading Hugo:

- https://github.com/gohugoio/hugo/issues/12886

**Comment by chalin** [comment]
Also hoping that the following will be addressed / accepted:

- https://github.com/gohugoio/hugo/pull/12901
