### ISSUE TITLE
Duplicate redirect rule

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#5531]
Duplicate redirect rule was introduced by (cc @open-telemetry/docs-pt-approvers):

- #5393

Here are the details:

```console
$ grep '/docs/instrumentation/\*' public/_redirects
/docs/instrumentation/*             /docs/languages/:splat
/docs/instrumentation/*             /pt/docs/languages/:splat
```

We need to mark the `redirects` entry as `en`-only.

I'm not sure how to provide more general guidance here. Maybe non-`en` locales will need to generally ignore `redirects` directives, or at least ask @open-telemetry/docs-maintainers when in doubt. Thoughts?

---

### Tasks

- [x] Add "`en`-only" comment to `en` page - #5532
- [x] Remove `redirects` entry from `content/pt/docs/languages/_index.md` - #5533
- [ ] Mention this soft convention in the Localization docs?

**Comment by edsoncelio** [comment]
Thanks @chalin!
Should I open a PR fixing that?
At least for now, I'll add a note about it in our localization guide.

**Comment by chalin** [comment]
Thanks @edsoncelio 🙌🏻. Yes, please submit a PR to remove the `redirects` entry. You might want to wait for #5532 to get merged first so that you can refer to the new commit hash.

**Comment by chalin** [comment]
#5532 has been merged @edsoncelio -- FYI. If you aren't available to submit the PR, let me know and I'll do it.

**Comment by edsoncelio** [comment]
> #5532 has been merged @edsoncelio -- FYI. If you aren't available to submit the PR, let me know and I'll do it.

The PR: https://github.com/open-telemetry/opentelemetry.io/pull/5533

**Comment by chalin** [comment]
Super, thank you @edsoncelio! Merged ✨

**Comment by chalin** [comment]
Going to consider this done for now. We can revisit later as needed.
