### ISSUE TITLE
[Meta] Migrate C++ API&SDK documentation to new structure

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#5686]
# Tasks

- [ ] Rename "Getting Started" to "Getting Started by Example"
- [ ] Replace Instrumentation, Libraries, Exporters pages with "Record Telemetry with the API", "Manage Telemetry with the SDK", "Configure the SDK" and "Configure the SDK" pages
- [ ] Add "Instrumentation ecosystem" page
- [ ] Add "Intro to OpenTelemetry C++" page

# Background

Based on [Restructure Language SDK & API documentation information architecture - #4853](https://github.com/open-telemetry/opentelemetry.io/discussions/4853) we rolled out an updated information architecture for the language API & SDK documentations for Java via #4966 and other PRs: https://opentelemetry.io/docs/languages/java/api/

As announced on the discussion and during a maintainer's call we want to roll out the same changes across all other languages. This is the meta issue for C++

cc @open-telemetry/cpp-approvers @open-telemetry/cpp-maintainers

**Comment by devatbosch** [comment]
Hi @svrnm ,

Wanted to know is this issue still valid and open if so I would like to take it up. Also, apart from the requirements listed in Tasks & Background section, is there anything else I need to take care of...

Please do let me know...

Thank You!

**Comment by svrnm** [comment]
@devatbosch this issue is still open, to address it, you would need to review the Java docs first and see how they can be translated to C++. This can be a step-by-step process

**Comment by agnes-sharan** [comment]
Hi @devatbosch are you still working on this?

**Comment by devatbosch** [comment]
Hi @agnes-sharan , no am not working on it. You may please take it over...

**Comment by agnes-sharan** [comment]
thank you, I'll like to be assigned to this please!

**Comment by svrnm** [comment]
@agnes-sharan please go ahead if you'd like to work on it, we are not assigning issues in this repo right now, also this is a meta issue with multiple pieces, so you can pick up from that list step-by-step. thank you
