### ISSUE TITLE
 [Meta] Migrate Go API&SDK documentation to new structure

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#5689]
# Tasks

- [ ] Rename "Getting Started" to "Getting Started by Example"
- [ ] Replace Instrumentation, Libraries, Exporters, Resources, Sampling pages with "Record Telemetry with the API", "Manage Telemetry with the SDK", "Configure the SDK" and "Configure the SDK" pages
- [ ] Add "Instrumentation ecosystem" page
- [ ] Add "Intro to OpenTelemetry Go" page
- [ ] Add any additional pages and resources that the Go SIG likes to add within their space

# Background

Based on [Restructure Language SDK & API documentation information architecture - #4853](https://github.com/open-telemetry/opentelemetry.io/discussions/4853) we rolled out an updated information architecture for the language API & SDK documentations for Java via #4966 and other PRs: https://opentelemetry.io/docs/languages/java/api/

As announced on the discussion and during a maintainer's call we want to roll out the same changes across all other languages. This is the meta issue for Go

cc @open-telemetry/go-approvers @open-telemetry/go-maintainers

**Comment by svrnm** [comment]
@vitorvasc you don't have to be a go maintainer, but the @open-telemetry/go-maintainers and @open-telemetry/go-approvers  will be the ones that need to approve any updates. I suggest that you start with some smaller changes and then work towards the bigger ones. Let me know if you need any assistance

**Comment by groantubes** [comment]
Hello, I would like to work on this issue

**Comment by vitorvasc** [comment]
Hi @groantubes!

Please note that this is a meta issue, which means it serves as a high-level tracker for several related tasks, rather than a single unit of work. That said, I'd suggest you splitting the work into smaller, manageable PRs to make the review process easier for everyone.

Please, let me know if you have any questions or blockers during the process! 🙂

**Comment by saurabhmj** [comment]
@svrnm / @vitorvasc  I'm happy to contribute to this. I have https://github.com/open-telemetry/opentelemetry.io/pull/11127 up for the title change.
