### ISSUE TITLE
[Meta] Migrate JavaScript API&SDK documentation to new structure

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#5690]
# Tasks

- [x] Rename "Getting Started" to "Getting Started by Example" - https://github.com/open-telemetry/opentelemetry.io/pull/9687
- [ ] Replace Instrumentation, Libraries, Exporters, Context, Propagation, Reources, Sampling pages with "Record Telemetry with the API", "Manage Telemetry with the SDK", "Configure the SDK" and "Configure the SDK" pages
- [ ] Add "Instrumentation ecosystem" page
- [ ] Add "Intro to OpenTelemetry JavaScript" page
- [ ] Review the Serverless & Benchmarks pages, if they can be incorporated into other pages 
- [ ] Add any additional pages and resources that the JavaScript SIG likes to add within their space

# Background

Based on [Restructure Language SDK & API documentation information architecture - #4853](https://github.com/open-telemetry/opentelemetry.io/discussions/4853) we rolled out an updated information architecture for the language API & SDK documentations for Java via #4966 and other PRs: https://opentelemetry.io/docs/languages/java/api/

As announced on the discussion and during a maintainer's call we want to roll out the same changes across all other languages. This is the meta issue for JavaScript

cc @open-telemetry/javascript-approvers @open-telemetry/javascript-maintainers

**Comment by DevpriyaDave** [comment]
Will start working on this.

**Comment by vitorvasc** [comment]
Thanks @DevpriyaDave!

Please note that this is a meta issue, which means it serves as a high-level tracker for several related tasks, rather than a single unit of work. That said, I'd suggest you splitting the work into smaller, manageable PRs to make the review process easier for everyone.

Please, let me know if you have any questions or blockers during the process! 🙂

**Comment by DevpriyaDave** [comment]
@svrnm @vitorvasc I just got around to looking into the additional steps for this issue (apologies for the delay). I'd like to confirm my approach before starting.
  
  I'm planning one atomic PR that:
  1. Moves contents of existing pages into new `api.md` and `sdk.md`
  2. Replaces the current instrumentation.md with the new "Instrumentation ecosystem" overview page
  3. Adds configuration.md (move any config related item in instrumentation.md to here)
  4. Deletes the pages that are consolidated
The reason for doing this atomically is that if only part lands, users experience might not be good navigating the js docs.

  Additionally, planning to add following redirect mapping

  /docs/languages/js/libraries  - sdk.md
  /docs/languages/js/exporters    - sdk.md
  /docs/languages/js/context      -  api.md
  /docs/languages/js/propagation   - api.md
  /docs/languages/js/resources    - sdk.md
  /docs/languages/js/sampling     -  sdk.md
  /docs/languages/js/api/tracing  -  api.md

Since this will be a large change (500+ lines), happy to open a draft PR first if that's easier to review. Let me know what you prefer.

**Comment by svrnm** [comment]
A draft PR sounds like a good idea. The less you can put in an atomic PR the better, but this has a bunch of cross dependencies so you might be right on your size assessment.
