### ISSUE TITLE
[Meta] Migrate Python API&SDK documentation to new structure

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#5692]
# Tasks

- [ ] Rename "Getting Started" to "Getting Started by Example"
- [ ] Replace Instrumentation, Libraries, Exporters, Propagation pages with "Record Telemetry with the API", "Manage Telemetry with the SDK", "Configure the SDK" and "Configure the SDK" pages
- [ ] Add "Instrumentation ecosystem" page
- [ ] Add "Intro to OpenTelemetry Python" page
- [ ] Review how the cookbook, distro, using mypy, benchmarks pages can be incorporated into the new structure
- [ ] Add any additional pages and resources that the Python SIG likes to add within their space

# Background

Based on [Restructure Language SDK & API documentation information architecture - #4853](https://github.com/open-telemetry/opentelemetry.io/discussions/4853) we rolled out an updated information architecture for the language API & SDK documentations for Java via #4966 and other PRs: https://opentelemetry.io/docs/languages/java/api/

As announced on the discussion and during a maintainer's call we want to roll out the same changes across all other languages. This is the meta issue for Python

cc @open-telemetry/python-approvers @open-telemetry/python-maintainers

**Comment by proxence** [comment]
Hello! I would like to work on this issue.

**Comment by vitorvasc** [comment]
Hi @proxence!

Please note that this is a meta issue, which means it serves as a high-level tracker for several related tasks, rather than a single unit of work. That said, I'd suggest you splitting the work into smaller, manageable PRs to make the review process easier for everyone.

Please, let me know if you have any questions or blockers during the process! 🙂
