### ISSUE TITLE
[Meta] Migrate Rust API&SDK documentation to new structure

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#5694]
# Tasks

- [ ] Rename "Getting Started" to "Getting Started by Example"
- [ ] Replace Instrumentation, Libraries, Exporters pages with "Record Telemetry with the API", "Manage Telemetry with the SDK", "Configure the SDK" and "Configure the SDK" pages
- [ ] Add "Instrumentation ecosystem" page
- [ ] Add "Intro to OpenTelemetry Rust" page
- [ ] Add any additional pages and resources that the Rust SIG likes to add within their space

# Background

Based on [Restructure Language SDK & API documentation information architecture - #4853](https://github.com/open-telemetry/opentelemetry.io/discussions/4853) we rolled out an updated information architecture for the language API & SDK documentations for Java via #4966 and other PRs: https://opentelemetry.io/docs/languages/java/api/

As announced on the discussion and during a maintainer's call we want to roll out the same changes across all other languages. This is the meta issue for Rust

cc @open-telemetry/rust-approvers @open-telemetry/rust-maintainers
