### ISSUE TITLE
Complete file setup for recommended use of docsy

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#744]
- [x] Switch to cncf/docsy repo, opentelemetry.io branch - #745
- [x] **Assets**
  - [x] Refactor and cleanup `assets/scss` - #746
    - [x] #751 
    - Related: #755
  - [x] #756
  - The following full overrides remain:
    - `assets/icons/logo.svg`
    - `assets/scss/_styles_project.scss`
    - `assets/scss/_variables_project.scss`
- [x] **Layouts**, these are the current overrides relative to docsy 2020/10, and the planned migration:
  - `layouts/_default/baseof.html` - **Leave in project**: hasn't changed in 3 years so there won't be any conflicts.
  - [x] `layouts/partials/head-css.html` - **Leave in project**:  partial override but one which will disappear once docsy is updated. Also see #641.
  - `layouts/partials/hooks/body-end.html` - **Leave in project** since this is a (full?) override.
  - [x] `layouts/partials/navbar.html` - drop this change - #810
  - [x] `layouts/partials/page-meta-links.html` - ~Move into docsy branch only after the upgrade.~ (All changes were upstreamed):
    - [x] **Waiting on**: https://github.com/google/docsy/pull/737
    - [x] #1053
  - [x] `layouts/partials/scripts.html` - **Leave in project**: partial override but one which will disappear once docsy is updated. Also see #641.
  - [x] Cleanup: #810

Related:

- #641
- #640
- https://github.com/etcd-io/website/issues/431
