### ISSUE TITLE
Host blog posts on website

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#845]
Steps to transitioning to the website-hosted blog:

- [x] Create Blog section - #1057
- [x] [@open-telemetry/blog-approvers]:
  - [x] Call for [@open-telemetry/blog-approvers] - https://lists.cncf.io/g/cncf-opentelemetry-comms/message/283
  - [x] https://github.com/open-telemetry/community/issues/953
  - [x] Add to README Roles section - #1064
  - [x] Add to CODEOWNERS - #1064
- [x] Create a blog [Hugo archetype file] - #1062
- [x] Add instructions for _Adding a blog post_, and create supporting archetypes:
  - #1062
  - #1139
- [x] Migrate references / abstracts linking to old posts:
  - [x] #1091
  - [x] #1136 & #1138
  - [x] #1137
  - [x] #1140
  - [x]  #1141
  - [x] #1142
  - Consider removing the `medium` archetype --> #1267
- Announcement that new blog posts will be hosted through the website:
  - Listserv - https://lists.cncf.io/g/cncf-opentelemetry-comms/message/305
  - Medium post to announce the move?

[@open-telemetry/blog-approvers]: https://github.com/orgs/open-telemetry/teams/blog-approvers
[Hugo archetype file]: https://gohugo.io/content-management/archetypes

---

Original opening comment:

Someone expressed the wish that blog posts be hosted directly on this site, but I can't recall who. Maybe @lizthegrey @tedsuo @austinlparker @mangotron? They are currently hosted on Medium at https://medium.com/opentelemetry.

Anyhow, we can use this issue to discuss the topic -- either before or after the next proposed post: https://lists.cncf.io/g/cncf-opentelemetry-comms/message/270 (cc @lalitb).

**Comment by austinlparker** [comment]
I did! We should do this in Q1.

**Comment by austinlparker** [comment]
AFAICT here's a rough plan/to-dos:

- [ ] Migrate existing Medium blog posts to /content/en/blog
- [ ] Figure out redirect strategy
- [ ] Tweak blog template if needed
- [ ] Create blog contribution guide
- [ ] Announce timeline to listserv

Probably some stuff I'm missing, but this should be a start.

**Comment by chalin** [comment]
@austinlparker do you want to make the announcement re. the blog's move (see the opening comment for the subtask). /cc @tedsuo

**Comment by chalin** [comment]
On the #otel-comms Slack @tedsuo, wrote “if we aren’t just about to do a migration ...”, what do you mean? I don’t think that we should migrate (copy) the old posts (we want single source for posts too). We might want to create entries with the same title and an abstract, but that simply refer readers to the medium page for the details. We’d set the canonical link to be the Medium page in that case. What do y’all think?

An alternative (or maybe in addition), I _might_ be able to create a dropdown menu with two links: one to the website blog and another to the Medium pages.

**Comment by tedsuo** [comment]
Ideally, we would copy the articles over, and set the original article as the canonical link so that SEO isn't a problem. Or at least create entries which redirect to the old blog articles, like you suggest (probably way less work, unless there's an easy markdown exporter for Medium). 

Otherwise, I'm concerned that the content of the old blog will be effectively lost. A lot of it is important and useful information, so it's worthwhile to preserve access. I hope that makes sense; @austinlparker listed this migration  as an action item, so I thought it had been discussed. Apologies for the surprise! :)

**Comment by chalin** [comment]
Thanks for the feedback @tedsuo.

> Ideally, we would copy the articles over, and set the original article as the canonical link so that SEO isn't a problem. Or at least create entries which redirect to the old blog articles, like you suggest (probably way less work, unless there's an easy markdown exporter for Medium).

Ok, I'll look into those options tomorrow.

**Comment by austinlparker** [comment]
Sorry for dropping the ball on this one, I meant to look into it after the last comms meeting but I was sidelined for a bit. In terms of conversion the open question I have is canonical URLs or redirects; I don't think there's a way to export markdown from Medium easily, I was already resigned to manually migrating the content. @chalin ping me on Slack and we'll sort something out once you have an idea about URLs/redirects.

**Comment by chalin** [comment]
No worries. I'll reach out later today.

**Comment by chalin** [comment]
This tracking issue is pretty much done, closing. We'll track the final issue via #1267.
