### ISSUE TITLE
Status page > Latest releases: not all links are to the latest release

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#905]
**Summary**: I'd like to suggest that we do away with the "Latest release" section of the status page because it isn't up-to-date, and interested readers can visit the SIG's landing page for a link to the latest release. WDYT @austinlparker?

**Work items**:

- [x] #929
- [x] #930
- [x] Drop script used to fetch release info - #931
- [x] Update submodule repos:
  - [x] Go: https://github.com/open-telemetry/opentelemetry-go/pull/2398
  - [x] Java: https://github.com/open-telemetry/opentelemetry-java/pull/3885
  - [x] PHP: https://github.com/open-telemetry/opentelemetry-php/pull/475
  - [x] Python: https://github.com/open-telemetry/opentelemetry-python/pull/2279
  - [x] Ruby: https://github.com/open-telemetry/opentelemetry-ruby/pull/1021
- [ ] Update submodules

**Details**:

The releases section of the status page now looks like this (as of 2021/11/11):

> <img width="400" alt="LR" src="https://user-images.githubusercontent.com/4140793/141289187-7cff0643-b3bf-47cb-9d04-aa4cf501e580.png">
Looking at this a bit more closely I'm noticing that some links refer to a version that is **not the latest release**:

- .NET: links to a **pre-release**
- PHP: links to a **pre-release**
- Ruby: links to a release that isn't the latest. Another problem here is that the Ruby SIG seems to release **separate packages** -- i.e., there is no single latest release.
  _The proper release info is given in the SIG's landing page_, https://opentelemetry.io/docs/ruby/.
- Erlang: links to an **archived repo**. 
  _The proper release info is given in the SIG's landing page_, https://opentelemetry.io/docs/erlang/.

Given that the landing pages for most language SIGs contain a link to the SIG's release page, I'd like to suggest that we do away with the "Latest release" section of the status page. WDYT @austinlparker? If you agree, I'll ensure that each SIG's landing page does indeed contain a link to releases.

**Comment by austinlparker** [comment]
sgtm

**Comment by austinlparker** [comment]
I believe if we remove this then we can nix the script that pulls release info as well and remove some cruft from the build.
